from handlers import users
from handlers import admin
from handlers import registration
from handlers import payment
from handlers import biometrics
from handlers import strength
from handlers import strength_capacity
from handlers import aerobic_capacity
from handlers import gymnastics
from handlers import profile
from handlers import freeze
